volumes:
  postgres_db:
services:
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django-postgres-kube
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    depends_on:
      - db