// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: content_tag.proto

package content_tag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                               // ID of the content tag.
	OrganizationId int32   `protobuf:"varint,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // ID of the organization that owns the content tag.
	Name           string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                            // Content tag name.
	BrandIds       []int32 `protobuf:"varint,4,rep,packed,name=brand_ids,json=brandIds,proto3" json:"brand_ids,omitempty"`            // The Brand IDs to have access to the content tag.
	CreatedAt      string  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                 // Timestamp of when the content tag was originally created.
	UpdatedAt      string  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                 // Timestamp of when the content tag was last updated.
}

func (x *ContentTag) Reset() {
	*x = ContentTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_content_tag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentTag) ProtoMessage() {}

func (x *ContentTag) ProtoReflect() protoreflect.Message {
	mi := &file_content_tag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentTag.ProtoReflect.Descriptor instead.
func (*ContentTag) Descriptor() ([]byte, []int) {
	return file_content_tag_proto_rawDescGZIP(), []int{0}
}

func (x *ContentTag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContentTag) GetOrganizationId() int32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *ContentTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContentTag) GetBrandIds() []int32 {
	if x != nil {
		return x.BrandIds
	}
	return nil
}

func (x *ContentTag) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ContentTag) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_content_tag_proto protoreflect.FileDescriptor

var file_content_tag_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54,
	0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x62,
	0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x61, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_content_tag_proto_rawDescOnce sync.Once
	file_content_tag_proto_rawDescData = file_content_tag_proto_rawDesc
)

func file_content_tag_proto_rawDescGZIP() []byte {
	file_content_tag_proto_rawDescOnce.Do(func() {
		file_content_tag_proto_rawDescData = protoimpl.X.CompressGZIP(file_content_tag_proto_rawDescData)
	})
	return file_content_tag_proto_rawDescData
}

var file_content_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_content_tag_proto_goTypes = []interface{}{
	(*ContentTag)(nil), // 0: ContentTag
}
var file_content_tag_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_content_tag_proto_init() }
func file_content_tag_proto_init() {
	if File_content_tag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_content_tag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_content_tag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_tag_proto_goTypes,
		DependencyIndexes: file_content_tag_proto_depIdxs,
		MessageInfos:      file_content_tag_proto_msgTypes,
	}.Build()
	File_content_tag_proto = out.File
	file_content_tag_proto_rawDesc = nil
	file_content_tag_proto_goTypes = nil
	file_content_tag_proto_depIdxs = nil
}
