kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-service
            port:
              number: 80

      - path: /static/
        pathType: Prefix
        backend:
          service:
            name: nginx-server-service
            port:
              number: 80