apiVersion: v1
kind: List
items:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: http-ingress
      namespace: backend-django
    spec:
      rules:
      - http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-service
                port:
                  number: 80

          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: nginx-server-service
                port:
                  number: 80

  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: http-ingress
      namespace: backend-go
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
    spec:
      rules:
      - http:
          paths:
          - path: /pbuf(/|$)(.*)  # skip `/pbuf` prefix internally
            pathType: Prefix
            backend:
              service:
                name: gin-service
                port:
                  number: 80