apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: backend-django
data:
  nginx.conf: |-
    events {}
    http {
      default_type application/octet-stream;
      include /etc/nginx/mime.types;

      server {
        listen 80;
        server_name localhost;
    
        location / {
          proxy_pass http://django-service; # change to gunicorn http://unix:/run/gunicorn.sock;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
        }
    
        location /static/ {
          autoindex on;
          alias /usr/share/nginx/static/;
        }
      }
    }