kind: Service
apiVersion: v1
metadata:
  name: nginx-server-service
  namespace: backend-django
spec:
  selector:
    app: nginx-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
