apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: backend-django
  labels:
    app: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              subPath: nginx.conf
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
            - name: staticfiles
              mountPath: /usr/share/nginx/static
              readOnly: true
      initContainers:
        - name: collectstatic
          image: docker.io/library/django_web:v1
          env:
            - name: STATIC_ROOT_PATH
              value: "/usr/share/nginx/static"
          command: ['python', 'manage.py', 'collectstatic', '--no-input']
          volumeMounts:
            - name: staticfiles
              mountPath: /usr/share/nginx/static
              readOnly: false
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: staticfiles
          emptyDir:
            sizeLimit: 500Mi

