apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: backend-django
  labels:
    app: postgres
data:
  postgresql.conf: |
    max_connections = 100
    shared_buffers = 256MB
    log_statement = 'all'