# commited secrets for tutorial purposes only
# for the real use case they should be created via command or use some secrets manager like vault
# example command for creating secrets:
# kubectl create secret generic postgres-database \
#  --namespace backend-django \
#  --from-string=DATABASE_URL="your-database-url"
#
# Secret is base64 encoded:
# echo -n "psql://postgres:postgres@postgres-service:5432/postgres" | base64
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: postgres-database
      namespace: backend-django
    type: Opaque
    data:
      DATABASE_URL: cHNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9wb3N0Z3Jlcw==
